spring:
  application:
    name: clbs-gateway-server

server:
  port: 8080

zuul:
  routes:
    culture-service:
      stripPrefix: false
      path: /api/culture/**
      url: http://localhost:8881
    user-service:
      stripPrefix: false
      path: /api/user/**
      url: http://localhost:8882
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
