spring:
  application:
    name: clbs-infomation-server

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
    registerWithEureka: false
    fetchRegistry: false
